Jamesbarford/holyc-lang

src/ast.c
src/ast.h
src/cctrl.c
src/compile.c
src/compile.h
src/holyc-lib/json.HC
src/holyc-lib/sqllite.HC
src/holyc-lib/tos.HH
src/lexer.c
src/lexer.h
src/main.c
src/prslib.c
src/prsutil.c
tests/29_macros.HC
tests/31_json.HC
tests/32_sql.HC

- allow for `#if` `#elif` & `defined`
- function prototypes no longer require named variables
- don't use `c` keywords for the name of anything
- `!` can be used in `EvalIntCostExpr`
- Update `29_macros.HC` tests
- Added other global definitions for int sizes

Feat: `#if` `#elif`,`defined()`  + function prototype updates

---

src/cctrl.c
src/main.c

- Fixes `hcc <file>.HC` so we don't have to do `hcc ./<file>.HC`.
- Can also handle `/<path>/<file>.HC` or `~/<path>/<file>.HC`
- restict file extensions to `.HC`, `.HH`, `.hc` and `.hh`

fix #1 - file path

---

src/ast.h
src/parser.c
tests/20_loops.HC

- Fixes `do-while`, the AST for a `while` was being used instead of `do-while` which meant it was not working
- Added a test for a `do-while` loop

Fix: do-while & test

---

README.md

- Fixed typos on README
- A code example & improved the `"hello, world\n!"` example

Chore: better README, fixed typos

---

src/lexer.c
tests/26_f64.HC

- Fixes parsing a number like: `.32` so the compiler can now handle `.32` and `0.32`.
- Updated a floating point test to reflect this change.

fix: for floating point parsing

---

README.md
src/cctrl.c
src/cctrl.h
src/holyc-lib/hashtable.HC
src/holyc-lib/memory.HC
src/holyc-lib/strings.HC
src/holyc-lib/tos.HH
src/lexer.c
src/main.c

- Fix the ordering of the entries after resizing
- Removed `MapIndex`
- Added tests.
- Re-formatted assembly.
- Feature can now do `-DSOME_VARIABLE`, implemented this so I could write tests in the holyc file
- Fixed bug with lexer for when the last token is a indentifier.
- Fixed bug with lexer for `#error`.
Might want to differentiate between preprocessor keywords and runtime keywords?

Fix - hashtables

---

src/main.c

- The ordering of the flags matters. `-o` would clash with `-obj` thus we need to esnure the longer flags come first.
- Check the output file has a different name from the input file.

Fix: commandline options

---

src/ast.c
src/ast.h
src/parser.c
src/prsutil.c
src/x86.c

- Static floats supported
- Static strings also supported
- `static auto str = "string";`, support for auto keyword with static variables.
- Fix for `is_static` being on a type, this would mutate the types in `ast.c` thus making _all_ int's static.

Fix: fixes for static floats and strings

---

src/lexer.c

- The buffer does not need free-ing as it is static

Fix: do not free static buffer!

---

src/parser.c

- Ensure that a size field on a struct is an integer of some description.

Fix: ensure range loop size is int type

---

src/parser.c
src/util.h

- Use a symbolic constant for the range loop index
- Added `str_lit` macro

use #define for range idx variable name

---

src/holyc-lib/tos.HH

- Added ifdef guards to the `tos.HH`

fix: sqlite3 is now optional

---

src/holyc-lib/tos.HH
src/holyc-lib/vector.HC

- Allow passing an explicit size parameter when creating a vector, set a default to `32`.

fix: default size parameter when creating a vector

---

src/CMakeLists.txt
src/aostr.c
src/aostr.h
src/cctrl.c
src/cctrl.h
src/compile.c
src/compile.h
src/holyc-lib/defs.HH
src/lexer.c
src/lexer.h
src/main.c
src/map.c
src/map.h
src/parser.c
src/prsasm.c
src/prslib.c
src/prsutil.c
src/prsutil.h
src/util.h

- Use a ring buffer for the lexer, this allows for significantly faster parsing as the tokens are now parsed on the fly when needed by the parse as opposed to a distinct step before parsing.
- Improve performance of `-run` command when on mac, pipe directly into gcc without writting to a file and use system to execute shell commands for running and removing.
- Better error reporting.

lexer uses a ring buffer, better error reporting

---

src/parser.c

- Good reminder to always run the tests and do a fresh install before merging

fix: if class is number do not do try to parse as an array

---

src/holyc-lib/vector.HC

- As the assembly has been corrected for handling floats, the `QSortGeneric` routine can be used for all vector types.

Refactor: use QSortGeneric internally

---

src/ast.c
src/ast.h
src/cctrl.h
src/map.c
src/map.h
src/parser.c
src/prslib.c
src/prslib.h
src/x86.c

- Use vector for function arguments
- Remove `paramtypes` as it was not used
- Delete function for extracting function types, despite being called the return was never really used

refactor: function arguments are vector

---

src/lexer.h
src/main.c
src/prslib.c

- Call `gcc` on a `.s` file
- fix for `&` on a class; e.g: `Ptr *ptr = &ex->entries[0]`, before this was not working.

Feat: gcc to assmble an assembly file, fix for dereferencing a class

---

src/holyc-lib/hashtable.HC
src/holyc-lib/io.HC
src/holyc-lib/memory.HC
src/holyc-lib/threads.HC
src/holyc-lib/tos.HH
src/holyc-lib/vector.HC

- `ReAlloc` Needs to call `MSize` in the assembly, implemented in HC for the time being
- Fixed `QSortGeneric`
- Added more prototypes for pthread

fix: ReAlloc issues, qsort

---

src/holyc-lib/hashtable.HC
src/holyc-lib/strings.HC
src/holyc-lib/vector.HC

- Fix for threshold contantly being `0, something to do with mixing floats and ints in arithmetic operations
- Fix for `StrNCpy`

fixes for hashtables threshold and StrNCpy

---

src/aostr.c
src/aostr.h
src/cctrl.c
src/transpiler.c

- prefer `aoStrCatFmt`, less bug prone than `aoStrCatPrintf`... Ideally we'd make `aoStrCatPrintf` internal and only use it for numbers.
- fix for character buffer null termination.

fix - use aoStrCatFmt

---

src/cctrl.c
src/lexer.c
src/prsutil.c

- Fixes a bug where the lexer would increment the line counter when parsing the character `\n`.
- Improved error message for mismatching types
- Use the severity color for the `^` underlining.

fix - error line reporting

---

src/compile.c
src/compile.h
src/main.c

- Pass through commandline options to `compile` functions
linked to: #120

refactor - pass options through to compile func

---

src/cctrl.c
src/cctrl.h
src/prslib.c
src/transpiler.c
src/x86.c

- Arrays in global and local scope like the below work, as do unary operators which before were doing something weird.
```hc
I64 arr[][2] = {
{1,2},
{3,4},
{5,6}
};
if (!arr[0][1]) {
"something!\n";
}
```

fix: array indexing and global arrays

---

src/main.c

Invoking hcc -<S/cfg> <file_name> creates an output file that discards everything, except the first 3 bytes of the file name. For instance, hcc -S hello.hc will create a file called hel.s, and the same with other holyc files.
Some other things to note
```hc
U0 Main() {}
Main;
```
In the above example, if the function `Main` doesn't end with a newline (that's an empty newline after `Main;`), but rather a nul-terminated character, hcc reports an error that  `;` wasn't given after the function name and crashes.
This shouldn't be an error though, it stops around here.
https://github.com/Jamesbarford/holyc-lang/blob/61a082428a6f53a744df6f0545105b42ab63e4b1/src/cctrl.c#L812-L816
This function `cctrlRewindUntilStrMatch()` calls `cctrlTokenPeek()` which returns `NULL`. Unfortunately I don't have …

src/main.c: fix chopped off output file name

---

src/main.c

- Don't use `safeSystem` for the run command as it causes a panic.

fix - run command

---

src/lexer.c

- `NULL` termination of a file was happening in the wrong place
Closes: #143

fix - compile files with no newline endings

---

src/holyc-lib/strings.HC

- This is a stop gap, the x86.c file should determine when to/not to emit a jump table. However this one was over 10k lines of code so felt appropriate to change manually.

fix - for jump table taking over 10k lines of code

---

Makefile
src/main.c

- Seems gcc-11 & gcc-12 work only if the CFLAGS in the Makefile is a string
- Fixed the return value being ignored from `system`

fix - change how flags are passed in Makefile

---

src/aostr.c
src/aostr.h
src/ast.c
src/ast.h
src/cctrl.c
src/cctrl.h
src/lexer.c
src/lexer.h
src/map.c
src/map.h
src/parser.c
src/prslib.c
src/tests/38_sizeof.HC
src/x86.c

Need to test this on Linux before merging.
- `sizeof(...)` a string now calculates the length of the string returning the correct number.
- Removed escaping logic from `x86.c`, escaping logic should only happen in one place.
- Refactored out `escape_string` as it was not used and was highly confusing (I don't really know what it did)
Closes: #146 #151

Fix - character counting

---

src/aostr.c
src/aostr.h
src/cctrl.c
src/cctrl.h
src/lexer.c
src/map.c
src/map.h
src/parser.c
src/prsasm.c
src/prsasm.h
src/prslib.c
src/prslib.h
src/x86.c

- Fix for global variables, also usable in assembly routines
- `sizeof(...)` usable in assembly
- Can define assembly in a function, disabled `inline` for these types of functions for the time being as they were very temperamental
```hc
U8 *str = "hello\n";
/* Cannot yet mix C and assembly directly */
U0 Print() {
asm {
PUSH    RBP
MOV     RSP, RBP
LEA     RDI, str[RIP]
CALL    printf
LEAVE
RET
}
}
U0 Main()
{
Print;
}
```

Fix global variables, allow assembly in a function

---

src/CMakeLists.txt
src/cli.c
src/main.c

- Get the git hash when building with CMake as opposed to at runtime
closes #168

fix - get git hash when compiling with cmake

---

Makefile
src/arena.c
src/ast.c
src/lexer.c
src/mempool.c
src/transpiler.c

- Fixes compiler warnings
- Changes to the Makefile should help surface more compiler warnings, tempted to put `-Werror`
- Remove string code from `mempool`, it does not need to be isolated from the rest of the project... I don't think unless `aoStr` eventually uses `mempool`

Fix all compiler warnings, remove string code from mempool

---

src/x86.c

remove call `cqto` in U64 divison which randomly causes floating point exception for values with bit63 set

Don't sign extend in unsigned division

---

src/cctrl.c
src/main.c

- Allows, hacky, cross compilation which seems to work. Though requires `clang --target=x86_64-apple-darwin`

Fix; MacOS Aarch64

---

src/ast.c
src/ast.h
src/cfg.c
src/containers.c
src/containers.h
src/holyc-lib/json.HC
src/lexer.c
src/parser.c
src/prslib.c
src/prslib.h
src/prsutil.c
src/prsutil.h
src/transpiler.c
src/x86.c

- Make the `Ast::kind` and `AstType::kind` enums (easier to keep track of than random ints)
- Modify code to support this
- Also fixes post incrementing pointers and some function pointer oddness

Chore; ast enums

---

src/ast.c
src/ast.h
src/parser.c
src/prslib.c
src/x86.c

Adding `NULL` as parameter would cause trying to print the ast to explode.
- Fix for the `sed` replace of long breaking the x64 codegen
- Also assign unique id's to lvars

Fix; for default function parameters
