src/x86.c
tests/34_global_array.HC

- Fix for global arrays of strings and static local arrays of strings
- Added tests.

fix: global string arrays

---

README.md
src/holyc-lib/strings.HC
src/holyc-lib/tos.HH
src/main.c

- Added a command for immediately running a file
- Created an implementation of `Atoi`

Feat: -run command and Atoi

---

src/ast.c
src/ast.h
src/cctrl.c
src/cctrl.h
src/compile.c
src/dict.c
src/dict.h
src/lexer.c
src/lexer.h
src/list.c
src/list.h
src/main.c
src/parser.c
src/parser.h
src/prsasm.c
src/prsasm.h
src/prslib.c
src/prslib.h
src/prsutil.c
src/prsutil.h
src/x86.c
src/x86.h

- From PascalCase to lowerCamelCase.

chore - unify casing of functions

---

src/holyc-lib/defs.HH
src/holyc-lib/io.HC
src/holyc-lib/tos.HH
tests/35_io.HC

fix - basic io on linux and tests

---

src/aostr.c
src/aostr.h
src/ast.c
src/ast.h
src/cfg.c
src/main.c
src/memory.c
src/prslib.c

- use `cfgHandleAstNode()` more liberaly
- marked in the code where IR could be made
- fix a bug with `char`
- simplified walking over the cfg

Fixes - cfg

---

src/cfg-print.c
src/cfg.c

- Fix do while control flow graph creation
- Something odd is happening with the file creation capabilities of `cfg-print.c`

fix: do-while cfg

---

Makefile
README.md
src/CMakeLists.txt
src/cctrl.c
src/holyc-lib/all.HC
src/main.c
src/tests/run.HC

- Conditionally compile with sqlite3
- Put and `ifdef` guard around the test
closes #62

Feat: make sqlite use optional

---

src/main.c

Fix: ordering of linking libs

---

src/cctrl.c
src/cctrl.h
src/main.c

- Use only one function to get the version

release: beta-v0.0.4

---

README.md
src/parser.c
src/tests/36_range_loop.HC

- Adds a range loop
- This saves a lot of typing, doesn't need to be used and has no overhead

Feat: range loop

---

src/tests/run.HC

- Simplify the test runner code

simplify test runner

---

src/cctrl.c
src/cctrl.h
src/parser.c
src/util.h
src/x86.c

- Allow class initialisers
- Allow arrays of classes to be initalised
- Refactored error messages
- Added compiler warning support

Feat: class array support

---

src/cctrl.c
src/config.h
src/main.c

- Makes more sense as an `#ifdef`

Fix: corrected check for Mac

---

src/cctrl.c
src/x86.c

- Can now use a variable to initalise the class

fix class initializing

---

src/parser.c
src/prslib.c

- Small fix for parsing classes
- Fix for a comparison where the string could be `NULL`

fix - class parsing and string comparison

---

src/transpiler.c

- add `\0` to the character buffer

fix - null terminate the character buffer

---

src/lexer.c
src/lexer.h

- Fix where the error is being reported.
- More `isatty` checking, think I need a utils folder than can handle some of that as I'm using it all over the place and it is an absolute mess.

Fix - error positioning

---

README.md
src/main.c
src/transpiler.c

- Added support to print assembly to stdout
- Added support to emit `inline` in the transpiler

Tweak - add inline and stdout support

---

src/holyc-lib/hashtable.HC

- `new_capacity` is not the right variable

fix - wrong variable

---

src/ast.c
src/transpiler.c

- Create `else if` rather than nested `else { if (<cond>) {} }`
- Fix up ast for classes... There is significant overlap with the transpiler in this regard.

Fix - else-if

---

src/holyc-lib/set.HC

- Implementation of redblack tree
- Implementation of IntSet built on redblack tree
- Built to help with advent of code!

feat: intset and redblack tree

---

src/holyc-lib/all.HC
src/holyc-lib/set.HC
src/holyc-lib/tos.HH

- Add the `RBTree` and `IntSet` headers and add to `all.HC`

feat: make set and rbtree usable

---

src/holyc-lib/math.HC
src/holyc-lib/tos.HH

- Absolute & Greatest Common Divisor assembly routines

feat - Abs and Gcd

---

src/holyc-lib/set.HC
src/holyc-lib/tos.HH
src/x86.c

- Fix for setting new value on a Red Black Tree
- Make `RBTreeHas` public
- Fix a use after free bug

fixes - x86 & rbtree

---

src/holyc-lib/net.HC

- Add `#ifdef`'s for linux specific `#defines` 
closes #113

fix - #defines net.HC for linux

---

README.md

- Document the warning with the linker
#119

docs - linker warning

---

Makefile
README.md
src/CMakeLists.txt
src/compile.c
src/compile.h
src/main.c
src/transpiler.c
src/transpiler.h

- Use a Make variable `INSTALL_PREFIX` to decide where the install path is
closes #120

feat - install dir

---

src/main.c

- Fix for creating `.s` files when compiling to `x86_64`

fix - assembly output file creation works & simplify logic

---

src/cctrl.h
src/prslib.c

release - bump version and remove print statements

---

src/x86.c

- `#if` guard the executable stack fix

fix - macos does not like progbits

---

src/x86.c

fix - asm format

---

README.md

- Remove bugs from readme to github issues
- Fix typo

update - README, remove known bugs from the README to github issues

---

Makefile

- Pass `CFLAGS` to the Makefile

feat - pass custom CFLAGS to makefile

---

src/main.c

- This causes havoc with string escaping by piping to gcc, writing to a file and then reading invoking `gcc` on it is far more stable.

fix - use the same run command on MacOs and Linux

---

src/holyc-lib/hashtable.HC
src/map.c

- This would often not work given particular inputs

fix - hashtable probing

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
src/CMakeLists.txt
src/cctrl.c
src/cctrl.h
src/cli.c
src/cli.h
src/compile.c
src/compile.h
src/config.h
src/main.c
src/transpiler.c
src/transpiler.h
src/util.h

- Better cli interface presentation
- Simplified bug ticket raising
- Created global `is_terminal` to save calling `isatty(...)` all over the place
- Created `__noreturn` along with a macro for `__attribute__((...))` in case it is not supported
- Parsing commandline arguments ordering can be more flexible

feat - nicer cli interface

---

src/compile.c

- Only print the tokens for the current source file

Feat - tokens only prints the tokens of the source file

---

src/aostr.c
src/ast.c
src/lexer.c
src/transpiler.c

- Escape strings in the lexer, unicode and emojis are not yet handled...

fix - inconsistent string escaping

---

src/cctrl.c

- fix for all errors not working

fix - remove calls to free which breaks all errors

---

src/version.h

- Bump the release, there have been some solid fixes and I'm about to massively refactor the AST.

chore; bump version

---

src/CMakeLists.txt
src/ast.c
src/cli.c
src/cli.h
src/main.c

- Add a cli command
- Remove phantom print statement

Chore; Groundwork for ir

---

src/CMakeLists.txt
src/ir-types.c
src/ir-types.h
src/ir.c
src/ir.h
src/main.c

Add more ir boilerplate and actually commit the ir files 🙄

Chore; More ir boilerplate
